// Vendors the four era typefaces into public/fonts so the game keeps its type offline: in the
// desktop build there is no CDN to ask, and on the web there is no third party to tell.
// All four are SIL Open Font License 1.1; NOTICE.md beside them carries the attribution.
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const OUT = new URL('../public/fonts/', import.meta.url);
// A modern browser UA, or the API answers with ttf instead of woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36';

const FAMILIES = [
  { name: 'Space Grotesk', spec: 'Space+Grotesk:wght@400;500;700', era: '2312' },
  { name: 'JetBrains Mono', spec: 'JetBrains+Mono:wght@400;700', era: '2148' },
  { name: 'Inter', spec: 'Inter:wght@400;600', era: '2031' },
  { name: 'Barlow Condensed', spec: 'Barlow+Condensed:wght@400;600', era: '2064' },
];

const slug = (s) => s.toLowerCase().replaceAll(' ', '-');

async function get(url, as = 'text') {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return as === 'text' ? res.text() : Buffer.from(await res.arrayBuffer());
}

await mkdir(OUT, { recursive: true });
const blocks = [];
let files = 0;

for (const fam of FAMILIES) {
  const css = await get(`https://fonts.googleapis.com/css2?family=${fam.spec}&display=swap`);
  // Keep only the latin and latin-ext cuts: the game is English and the rest is dead weight.
  const faces = css.split('/*').filter((c) => /^\s*(latin|latin-ext)\s*\*\//.test(c));
  let n = 0;
  for (const face of faces) {
    const url = /src:\s*url\((https:[^)]+)\)/.exec(face)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(face)?.[1] ?? '400';
    const subset = /^\s*(latin-ext|latin)\s*\*\//.exec(face)[1];
    if (!url) continue;
    const file = `${slug(fam.name)}-${weight}-${subset}.woff2`;
    const bytes = await get(url, 'bin');
    await writeFile(new URL(file, OUT), bytes);
    files++;
    n++;
    const range = /unicode-range:\s*([^;]+);/.exec(face)?.[1];
    blocks.push(`@font-face {
  font-family: '${fam.name}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('./${file}') format('woff2');${range ? `\n  unicode-range: ${range};` : ''}
}`);
  }
  console.log(`${fam.name.padEnd(18)} ${String(n).padStart(2)} cuts  (${fam.era})`);
}

await writeFile(new URL('fonts.css', OUT),
  `/* Generated by scripts/fetch-fonts.mjs. The four era typefaces, served from the app itself. */\n${blocks.join('\n\n')}\n`);
console.log(`\n${files} files in public/fonts, plus fonts.css`);

const notice = new URL('NOTICE.md', OUT);
if (!existsSync(notice)) {
  await writeFile(notice, `# Typefaces

Provenance uses four typefaces, one per era. All four are licensed under the
SIL Open Font License 1.1, which permits bundling and redistribution.

| Typeface | Era | Designer | License |
| --- | --- | --- | --- |
| Space Grotesk | 2312 | Florian Karsten | SIL OFL 1.1 |
| JetBrains Mono | 2148 | JetBrains | SIL OFL 1.1 |
| Inter | 2031 | Rasmus Andersson | SIL OFL 1.1 |
| Barlow Condensed | 2064 | Jeremy Tribby | SIL OFL 1.1 |

The files here are the latin and latin-ext cuts, fetched from Google Fonts by
\`npm run fonts\`. The full license text travels with each project upstream.
`);
}
void readFile;
